logging.level.root=DEBUG
logging.level.com.thai.pham=DEBUG

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.sql.init.mode=always
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

server.error.include-stacktrace=on_params
server.error.include-message=always