spring.application.name=inventory-service

spring.datasource.url=jdbc:postgresql://postgres_db:${DB_PORT:5432}/my_database
spring.datasource.username=${DB_USER:my_user}
spring.datasource.password=${DB_PASS:my_password}

spring.datasource.read_url=jdbc:postgresql://postgres_db:5433/my_database
spring.datasource.read_username=${DB_USER:my_user}
spring.datasource.read_password=${DB_PASS:my_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

database.master.url.jdbc.postgresql=//pg-master:${DB_PORT:5432}/app_db
database.master.username=db_user
database.master.password=db_pass
database.slaves.slave1=jdbc:postgresql://pg-slave-1:${DB_PORT:5432}/app_db
database.slaves.slave2=jdbc:postgresql://pg-slave-2:${DB_PORT:5432}/app_db
database.slaves.slave3=jdbc:postgresql://pg-slave-3:${DB_PORT:5432}/app_db
database.slaves.slave4=jdbc:postgresql://pg-slave-4:${DB_PORT:5432}/app_db
database.slaves.slave5=jdbc:postgresql://pg-slave-5:${DB_PORT:5432}/app_db

spring.data.redis.host=${REDIS_PORT:localhost}
spring.data.redis.port=${REDIS_HOST:6379}

server.port = ${INVENTORY_SERVER_PORT:8080}

spring.cache.type=redis

springdoc.api-docs.path=/{INVENTORY_DOC_PATH:api_doc}