spring.application.name=inventory-service

spring.datasource.username=${DB_USER:my_user}
spring.datasource.password=${DB_PASS:my_password}
spring.datasource.slave.username=${DB_SLAVE_USER:my_user_slave}
spring.datasource.slave.password=${DB_SLAVE_PASS:my_password_slave}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

database.master.url=jdbc\:postgresql\://pg-master\:${DB_PORT:5432}/${DB_NAME:app_db}
database.slaves.slave1.url=jdbc\:postgresql\://pg-slave-1\:${DB_PORT:5432}/${DB_NAME:app_db}
#database.slaves.slave2.url=jdbc:postgresql://pg-slave-2:${DB_PORT:5432}/${DB_NAME:app_db}
#database.slaves.slave3.url=jdbc:postgresql://pg-slave-3:${DB_PORT:5432}/${DB_NAME:app_db}
#database.slaves.slave4.url=jdbc:postgresql://pg-slave-4:${DB_PORT:5432}/${DB_NAME:app_db}
#database.slaves.slave5.url=jdbc:postgresql://pg-slave-5:${DB_PORT:5432}/${DB_NAME:app_db}
database.replication.count=1

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.leak-detection-threshold=10000

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

server.port = ${INVENTORY_SERVER_PORT:8080}

spring.cache.type=redis

springdoc.swagger-ui.path=/${INVENTORY_DOC_PATH:api_doc}

logging.level.root=INFO
logging.level.com.thai.pham=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n
