spring.datasource.url=jdbc:postgresql://postgres_db:5432/my_database
spring.datasource.username=my_user
spring.datasource.password=my_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
