spring.datasource.url=jdbc:postgresql://postgres_db:5432/my_database
spring.datasource.username=my_user
spring.datasource.password=my_password

spring.datasource.read_url=jdbc:postgresql://postgres_db:5433/my_database
spring.datasource.read_username=my_user
spring.datasource.read_password=my_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

database.master.url.jdbc.postgresql=//pg-master:5432/app_db
database.master.username=db_user
database.master.password=db_pass
database.slaves.slave1=jdbc:postgresql://pg-slave-1:5432/app_db
database.slaves.slave2=jdbc:postgresql://pg-slave-2:5432/app_db
database.slaves.slave3=jdbc:postgresql://pg-slave-3:5432/app_db
database.slaves.slave4=jdbc:postgresql://pg-slave-4:5432/app_db
database.slaves.slave5=jdbc:postgresql://pg-slave-5:5432/app_db

spring.data.redis.host=localhost
spring.data.redis.port=6379